pi1/class.tx_ttaddress_pi1.php

The Placeholder will not display on TYPO3 6.2.27.
This will be fix it.

[BUGFIX] fixed placeholderImage output

---

res/default_hcard.htm
static/pi1/setup.txt

I've added the corresponding [Schema.org](http://schema.org/Person) attributes to the vcard.
This helps structuring the information and improves indexing for search engines.
The resulting markup looks like the following:
```html
<address class="vcard" itemscope itemtype="http://schema.org/Person">
<span class="fn" item="name">
<span class="given-name" item="givenName">Firstname</span>
<span class="additional-name" item="additionalName">Middlename</span>
<span class="family-name" item="familyName">Lastname</span>
</span>
<div class="org" item="worksFor">Organization</div>
<a href="mailto:info@mailaddress.com" class="email" item="email">info@mailaddress.com</a>
<div class="adr" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
<div class="street-address" …
```

Feature: Schema.org attributes

---

pi1/flexform.xml

Fixes the language labels for the recursive option in flexform
to point to the correct language file.

[BUGFIX] Wrong language labels for recursive option

---

Configuration/TCA/tt_address.php

GeneralUtility::compat_version has been deprecated with TYPO3 v8 and
removed with v9, use direct calls to
VersionNumberUtility::convertVersionNumberToInteger() instead, those
even work in v6.2

[TASK] Usage of deprecated call to compat_version()

---

pi1/class.tx_ttaddress_pi1.php

Configuration values of type integer are ignored when rendering FILE cObjects during option split. Fixes https://github.com/FriendsOfTYPO3/tt_address/issues/38

Use string values in typoscript configuration

---

pi1/class.tx_ttaddress_pi1.php

When using the Addresses-Plugin Page Content with Typo3 v7 running on PostgreSQL, there is a frontend error.
Reason: Double quotes.
Solution: Replace with escaped single quotes, similar to line #285

Postgresql compatibility

---

Classes/Controller/LegacyPluginController.php

The query in \FriendsOfTYPO3\TtAddress\Controller\LegacyPluginController::getGroupsForAddress contains 2 bugs which cause Exceptions:
* The table alias "c" is defined for the table sys_category, but the alias is not used as the $fromAlias in the table join 
This caused the Doctrine\DBAL\Query\QueryException:
The given alias '`sys_category`' is not part of any FROM or JOIN clause table. The currently registered aliases are: `c`.
* The condition values for "mm.tablenames" and "mm.fieldname" are not escaped and therefore not quoted
This caused a Doctrine\DBAL\Exception\InvalidFieldNameException: Unknown column 'tt_address' in 'where clause' | Unknown column 'categories' in 'where clause'
The problems were tested and fixed with TYPO3 8.7.20

[BUGFIX] fix get groups query for address in legacy plugin controller

---

.github/ISSUE_TEMPLATE/Support_question.md

Use correct slack channel and stackoverflow tag in support question issue template.

Use correct slack and stackoverflow info in issue template

---

Classes/Controller/LegacyPluginController.php

The elvis operator :? leads to TRUE resulting in pid 1 and not
to the value of $this->ffData['pages']
Closes: #138

[BUGFIX] Overwriting of storage pid from flexform

---

Configuration/TypoScript/setup.typoscript
Resources/Private/Partials/ListItem.html

[TASK ]Always include "pages" in overrideFlexformSettingsIfEmpty
In order to override the storagePage by TypoScript, the setting
"pages" must be included in overrideFlexformSettingsIfEmpty. This
setting should be provided by default.
[BUGFIX] Fixed missing title attribute in links to detail page

[TASK] Minor bugfiles and improvements

---

Configuration/TCA/Overrides/tt_address.php
Configuration/TCA/tt_address.php

This commit adds "allowLanguageSynchronization" to nearly all TCA
fields, so user can decide, if value of default language should be
used or not.
Excepted fields: fender, first_name, middle_name, last_name
Refs. #160

[FEATURE] Added allowLanguageSynchronization to TCA

---

Classes/Updates/MigrateLegacyPlugin.php
Tests/Functional/Fixtures/tt_content.xml

When running the migration task it has to be ensured, only flexform
with consistent end expected keys in the array will be migrated.

[TASK] Skip inconsistent flexform in migration task

---

Configuration/TCA/tt_address.php

Hide building and room fields by default for users to make them available in access control options.

[TASK] Make building and room field available in access control options

---

Configuration/TCA/tt_address.php

'Incorrect integer value: '' for column 'l10n_parent' at row 1' (tt_address:NEW5cd1552965f6b253387324) on copy&paste tt_address record

fixed: SQL error on copy&paste record

---

Configuration/TCA/tt_address.php

The combined name field of a localized record is updated when values
of the fields 'first_name', 'middle_name' or 'last_name' were edited
in the original record.
Resolves: #259

[BUGFIX]: Sync name field in localized records

---

Configuration/TypoScript/setup.typoscript

added some more setup variables to make it more easy for admins using the backend typoscript browser or analyser. 
added a new setup variable settings.map.singlePid to be able to show a link to the single view in the map info bubble; please see proposal in rendering section of partial Maps.html and consider publishing it. 
Settings displayMode, groupsCombination, sortBy, sortOrder are not working yet due to having default values in plugin.
Would you consider to change the default values of these fields in the plugin' selectors to something labeled like 'defined by typoscript'?
This way administrators would have the possiblity to set global defaults for plugins by typoscript. 
Setting overrideFlexformSettingsIfEmpty can be extended by the fields displayMode, groupsCombination, sortBy, …

extend TS setup for ease of use

---

Resources/Public/JavaScript/Frontend/Leaflet.js

Event listener on DOMContentLoaded does not work with scripts which are loaded async.
With TYPO3 this could e.g. happen with EXT:scriptmerger
Thus we listen only if document.readyState is loading, otherwise we can already fire as DOM is loaded already.

[BUGFIX] Load map also if scripts are loaded async

---

Configuration/TCA/tt_address.php
ext_tables.sql

Adding fe_group to palette access. This allows for limiting access of specific address records to frontend user groups.
Resolves ticket #279

[TASK] Add fe_group to palette access

---

Configuration/TCA/tt_address.php

Use TYPO3 version switch for field names locallang of field sys_language_uid.
#304

Fix TCA locallang for field sys_language_uid

---

Configuration/FlexForms/List.xml

Currently it's not possible to have more than 20 selected categories. The limit is unnecessary and therefore removed also for singleRecords and pages.

[TASK] Remove unnecessary limit

---

Configuration/FlexForms/List.xml

The property show_thumbs for type=group is obsolete and
has been dropped from TCA in TYPO3 8.6.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.6/Deprecation-79440-TcaChanges.html

[TASK] Remove show_thumbs in Flexform

---

Configuration/FlexForms/List.xml

The option `[config][autoSizeMax]` have no influence on the rendering of FormEngine select field configured with `'renderType' => 'selectTree'` anymore.
The option `autosizemax` has been dropped as the `size` can be used as maximum height.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.3/Breaking-77081-RemovedTCASelectTreeOptions.html

[BUGFIX] Set proper size of flexform settings.groups

---

Resources/Private/.htaccess

Resolves: #354
The current code in .htaccess works for Apache 2.2.x or with the compat-extension in 2.4.x. Clean this up.

Compatibility with Apache 2.4.x

---

Configuration/FlexForms/List.xml

- Add range to from 1 to n to flexform settings.paginate.itemsPerPage (max value should be 99999 because size of field is 5).
- Change eval in settings.paginate.itemsPerPage from "trim,intval" to "trim,int" to get number evaluation in BE form.

Enhance List.xml Flexform

---

Classes/Domain/Model/Dto/Settings.php
Configuration/TCA/Overrides/tt_address.php
Tests/Unit/Controller/AddressControllerTest.php

If TYPO3 11 is used, the setting `newPagination` must be ignored as it
is the only option anyway.
Resolves: #377

[BUGFIX] Ignore newPagination setting for TYPO3 11

---

Documentation/Includes.txt
Documentation/Settings.cfg
Documentation/Tutorials/Index.rst
Documentation/Tutorials/Linkhandler.rst

Even if you've read the documentation you have to find out all the parameters etc. So I find it usefull to have a ready-to-use example just like in EXT_news.

[DOCS] Provide LinkHandler configuration

---

Configuration/TCA/tt_address.php

This will copy the field value of the default language record over to the field of the localized record. Since today, it is possible that the gender changes for a single person, and this should also synchronize with translations of the record.
Resolves: #448

[BUGFIX] Set localization mode for gender to exclude

---

Classes/Evaluation/LatitudeEvaluation.php
Classes/Evaluation/LongitudeEvaluation.php
Classes/Evaluation/TelephoneEvaluation.php
Configuration/JavaScriptModules.php
Resources/Public/JavaScript/esm/telephone-evaluation.js

* migrate inline JavaScript to ES6 module
* remove superfluous empty `returnFieldJS()` methods
Additionally https://review.typo3.org/c/Packages/TYPO3.CMS/+/79017 is required for correctly loading requireJS with CSP nonce values.

[TASK] Migrate custom form field evaluation (returnFieldJS)

---

Classes/FormEngine/FieldControl/LocationMapWizard.php

Using the URL /search/ with trailing slashe is no longer supported
see https://github.com/osm-search/Nominatim/issues/3134

[FIX] adapt nominatim API URL

---

Classes/Hooks/Tca/Label.php

The code has been adjusted to handle situations where the UID is not numeric in the Label.php class (e.g. a new record). Instead of directly casting the UID to an integer, it is first checked whether the UID is numeric. If it is not, the row is fetched directly from the parameters. This aims to prevent potential casting errors and provides more robust handling for uid parameters.
Resolves: #511

[BUGFIX] Cannot add new address record in TYPO3 v12 PHP 8.2

---

Classes/Command/GeocodeCommand.php

Prevents the following error with PHP 8.2 and TYPO3 12.4.10:
Fatal error: Declaration of FriendsOfTYPO3\TtAddress\Command\GeocodeCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/friendsoftypo3/tt-address/Classes/Command/GeocodeCommand.php on line 46

Prevent Fatal Error in TYPO3 12.4

---

composer.json

This clarifies compatibility and avoids unexpected updates.
See https://github.com/FriendsOfTYPO3/tt_address/pull/516

Explicitly require symfony/console

---

Classes/Database/QueryGenerator.php
Classes/Service/GeocodeService.php

In Doctrine DBAL v4, as described in the [documentation](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Database/QueryBuilder/Index.html#database-query-builder-create-named-parameter), support for using the `\PDO::PARAM_*` constants has been dropped in favor of the enum types. This should be migrated to `Connection::PARAM_*` in order to be compatible with TYPO3 v13 later on. `Connection::PARAM_*` can already be used now as it is compatible with TYPO3 11 and 12.

[TASK] Use Connection instead of PDO

---

Classes/FormEngine/TtAddressPreviewRenderer.php

In TYPO3 v12.4.17 the method `StandardContentPreviewRenderer::renderContentElementPreviewFromFluidTemplate` has [been changed](https://github.com/TYPO3/typo3/commit/a96746560a5bd9877a91e35ea5ce86432c12c996#diff-cb640d568c5e22f675f12a05f845b81306fd169f2296180ea6b9bcb681843823L249). This PR makes the `TtAddressPreviewRenderer` compatible again.

[BUGFIX] Make preview renderer compatible with v12.4.17

---

Classes/Domain/Model/Address.php

Fixes Extbase sometimes assumes the Category class is found in same folder as Address. To fix this, we use the FQDN of the Category class.
I sadly cannot state the clear circumstances, we encountered this error on TYPO3 11.5.41 and done this patch to fix it.
Nevertheless i think its never wrong to put the FQDN in the ObjectStorage generic, i think it just has been done by accident in commit https://github.com/FriendsOfTYPO3/tt_address/commit/4341d2ec4301f7ac8537c2277b7de89fc9761081.

[BUGFIX] Fixes unspecific Category Class
