FriendsOfTYPO3/tt_address

- ext_typoscript_setup.txt
in sql field was linkedin and in model property was linkedIn so i added mapOnProperty in setup.txt
> [BUGFIX] linkedIn property was not fetching data

- Configuration/TCA/tt_address.php
Avoid deprecated messages for > TYPO3 7.x
> Fix deprecated message: iconfile and wizard

- pi1/class.tx_ttaddress_pi1.php
This fixes a small typo for the conf of linkedin
> [BUGFIX] Fix small typo

- Classes/Updates/AddressGroupToSysCategory.php
- composer.json
- ext_emconf.php
Use array syntax for PHP 5.3.x
> [BUGFIX] Wrong error syntax for array

- Classes/Domain/Model/Address.php
I've added some basic getter and setter methods for categories.
In a projects of mine, I've injected `tt_address` and tried to access the categories via `getCategories()`but unfortunately this method is not implemented at the moment. Would be a nice little addition.
> Feature: categories

- Configuration/TCA/tt_address.php
change `birthday` from date to `datetime,int` due to mysql-strict problems 
fixes #68
> Change birthday - eval

- Classes/Updates/MigrateLegacyPlugin.php
- Documentation/Administration/Updating/Index.rst
- Tests/Functional/Fixtures/tt_content.xml
- Tests/Functional/Updates/MigrateLegacyPluginTest.php
- ext_localconf.php
> [TASK] Add migration of legacy plugins to extbase plugins

- Classes/Domain/Repository/AddressRepository.php
- Tests/Functional/Repository/AddressRepositoryTest.php
> [BUGFIX] Respect sorting field in customSelection

- Classes/Controller/AddressController.php
- Classes/Domain/Model/Dto/Demand.php
- Classes/Domain/Repository/AddressRepository.php
- Configuration/FlexForms/List.xml
- Resources/Private/Language/ff/locallang_ff.xlf
- Tests/Functional/Fixtures/tt_address.xml
- Tests/Functional/Repository/AddressRepositoryTest.php
- Tests/Unit/Domain/Model/Dto/DemandTest.php
> [FEATURE Add subcategory flag

- Classes/Domain/Model/Dto/Settings.php
- Classes/Evaluation/TelephoneEvaluation.php
- Tests/Unit/Domain/Model/Dto/SettingsTest.php
- Tests/Unit/Evaluation/TelephoneEvaluationTest.php
- ext_conf_template.txt
> [FEATURE] Make telephone regex configurable

- Classes/Domain/Model/Address.php
- Resources/Private/Partials/Address.html
- Tests/Unit/Domain/Model/AddressTest.php
> [BUGFIX] Show link without attributes

- Classes/Domain/Repository/AddressRepository.php
> [BUGFIX] Check for invalid sorting field

- Classes/Utility/TypoScript.php
- Configuration/TypoScript/setup.typoscript
- Tests/Unit/Utility/TypoScriptTest.php
> [BUGFIX] Respect bool values in overrideFlexformSettingsIfEmpty

- Configuration/TCA/tt_address.php
- Resources/Private/Language/de.locallang_db.xlf
- Resources/Private/Language/locallang_db.xlf
> [TASK] Added "various" as additional option for gender field

- Build/Local/phpunit.xml
- Build/UnitTests.xml
- Classes/Updates/MigrateLegacyPlugin.php
- Classes/Updates/TypoScriptTemplateLocation.php
- Tests/Unit/Updates/MigrationLegacyPluginTest.php
- Tests/Unit/Updates/TypoScriptTemplateLocationTest.php
> [BUGFIX] Fix failing update wizard

- Resources/Private/Partials/Full.html
The condition must be outside the curly braces.
Resolves: #257
> Fix syntax in count-condition

- Configuration/TCA/tt_address.php
> [BUGFIX] replace displayCondition for slug field

- Classes/Utility/TypoScript.php
- Tests/Unit/Utility/TypoScriptTest.php
> [BUGFIX] Change check if TS setting should be overriden via flexforms

- ext_localconf.php
> [BUGFIX] Remove trailing comma to keep compatibility with PHP 7.2

- Classes/Domain/Model/Address.php
would be nice to have hidden-attribute in model, so that it can be accessed via Extbase
> add hidden to model

- Resources/Private/Partials/Full.html
- Resources/Private/Partials/ListItem.html
> [BUGFIX] Use the correct ImageReference in partials

- ext_tables.sql
> [BUGFIX] Make table key uf8mb4 compatible

- ext_tables.sql
> [TASK] Change sql index name to avoid a name conflict

- Classes/Domain/Model/Address.php
- Documentation/Tutorials/Templates/GroupAddressRecords/Index.rst
- Documentation/Tutorials/Templates/Index.rst
With having a firstCategory property, it would easyly possible
to implement a grouping by category in Fluid -
e.g. for a category based accordeon.
Resolves: #382
> [FEATURE] implement firstCategory property

- Classes/Domain/Model/Address.php
- Classes/Utility/PropertyModification.php
- Classes/ViewHelpers/Clean/DomainViewHelper.php
- Classes/ViewHelpers/Clean/PhoneNumberViewHelper.php
Add ViewHelpers to use same logic as in model to modify phone number and domain
Resolves: #389
> [FEATURE] Extract property modification to utility

- Documentation/Administration/Updating/Index.rst
solves https://github.com/FriendsOfTYPO3/tt_address/issues/401
> [DOCS] Information on updating from v5.x to 6.0

- Classes/Controller/AddressController.php
- Tests/Unit/Controller/AddressControllerTest.php
Check sortby against tca but allow overriding it
> [FEATURE] Allow sortBy by override

- composer.json
Added new commit regarding additional sources (TER, repository and docs.typo3.org) in composer.json.
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/185
> [TASK] Align with new TYPO3 documentation standards (follow-up) 

- Classes/Hooks/Tca/Label.php
> [TASK] int cast for pid value

- Resources/Private/Partials/Pagination.html
Add correct labels to title tags
> [BUGFIX] Title values to new labels

- Classes/Controller/AddressController.php
> [BUGFIX] Prevent undefined array key "groups"

- Classes/Domain/Model/Dto/Settings.php
Fixes #452 by declaring $newPagination.
> [BUGFIX] Declare $newPagination

- Classes/Domain/Model/Address.php
- Configuration/TCA/tt_address.php
- Resources/Private/Language/locallang_db.xlf
- ext_tables.sql
Hi Georg,
I know there was once a discussion about social channels, but I think tt_address should support at least the most used ones. So I added Instagram and TikTok to the code. Would be happy if you launch it with the next release.
Liebe Grüße
Matthias
> Adding Instagram + TikTok to social details

- ext_conf_template.txt
See comments in #157 (yeah, it took some time...)
> Add settings for telephone regex again

- Resources/Public/JavaScript/Frontend/GoogleMaps.js
Adjust the code that manages address data in the Frontend to code used in Leaflet.js. Resolves issue #522.
> [BUGFIX]  FE Error: Uncaught TypeError: item.getAttribute #522

- Resources/Public/JavaScript/esm/leaflet-backend.js
Inside the nested async function of `geocode()` you have no access to `this`. So I removed the nested function and defined `geocode` as async itself. Then it works.
> fix async geocode function

- Documentation/Configuration/TypoScript/Index.rst
- Resources/Private/Partials/Maps.html
- Resources/Public/JavaScript/Frontend/GoogleMaps.js
> Migrate deprecated google marker to google advanced marker

- .editorconfig
Use the same settings like the Core and tabs for makefiles to prevent errors.
> [TASK] Update .editorconfig

- Configuration/TCA/tt_address.php
Adds a new tab "Extended" at the end of the tt-address TCA
see #582
> [feat] Add Extended tab in TCA

- Documentation/Administration/Installation/Index.rst
- Documentation/Administration/Updating/Index.rst
- Documentation/Configuration/ExtensionSettings/Index.rst
- Documentation/Introduction/Index.rst
> update supported version TYPO3 12 and 13
